### ISSUE TITLE
Add keyboard shortcut for “new sequence” box

### ISSUE THREAD

**Issue by mitch-fen** [genkimaps/wildcam#39]
Suggest "n" as hotkey. Would allow tabbing through all essential values without needing to use mouse.

**Comment by genkimaps** [comment]
@mitch-fen Is this a modal keyboard shortcut that is only active when the Identify window is open?

**Comment by mitch-fen** [comment]
@genkimaps That would likely be the most sensical option, but if it's considerably easier to have it as a general shortcut/flag (like the others), then that shouldn't be a problem either.
