### ISSUE TITLE
Add field for collar number

### ISSUE THREAD

**Issue by mitch-fen** [genkimaps/wildcam#45]
For cases where collars are visible (collar = T), an input box for collar number would be great. We've previously been using the comment field for this, but it tends to make post processing difficult due to the various non-numeric characters used by different classifiers (i.e collar # = 5, collar 5, collar = 5). 

This box would need to be able to accept multiple numbers as well, for cases where more than one collared individual is visible in an image (i.e. a herd of collared men goats).

**Comment by genkimaps** [comment]
@mitch-fen 
To clarify, all collars will be a number, correct?  I'm thinking of making it a field with tags, similar to this: http://jsfiddle.net/alanng/zg1paLsj/ 

Internally, it would be stored as comma-separated data.  Do you also need to query this data in the interface (e.g. filtering by a specific collar number) or is that something you can save for when you have downloaded all the data?

**Comment by mitch-fen** [comment]
@genkimaps 

For the existing projects, yes, all will be numbered (or unknown/not identifiable). For projects in the past though we've also had features such as different colour combos/bands of tape used to ID individuals. These could likely also be created within that same tagging framework I believe, instead of numbers.

We shouldn't have any need to query by collar number via the GUI, so long as we're able to query by collar in general. This allows us to double check the ID's for all collars prior to downloading.

**Comment by wildcole** [comment]
I don’t know how to send messages within github yet :/

But yes: not all collars will necessarily be numbers. (for example in Richardson/Algar projects, I don’t think we see numbers)

Mitch: I wonder if we should be generalizing to a field for “Mark” (T/F) which could be collar, tag, etc. And then a second field for Mark Type (e.g. “collar”) and perhaps a third for Mark ID (could be number or perhaps text [e.g. colour])?

I’m trying to anticipate future projects but would that make things too complex for your shorter-term needs?

**Comment by mitch-fen** [comment]
@wildcole 

I think that could potentially be a good solution for leaving the door open to future changes and projects. The compromise would be more steps in the identification process, but at least for my purposes there are relatively so few collared animals that it isn't a major concern at all!

@genkimaps 

My interpretation of what Cole has outlined would be a T/F checkbox for "Marked", a dropdown for "Mark Type" with options ["Collar", "Tag", "Brand", "Other"], and then something like the Select2 tag you proposed above for individual ID.

**Comment by genkimaps** [comment]
@wildcole OK that makes it very clear, thanks.  The T/F checkbox and other widgets will add some complexity to the interface, but it's doable.  Cole, FYI I don't think github has a separate messaging system, the intent is to use these comments to communicate.

**Comment by genkimaps** [comment]
@wildcole @mitch-fen  Is it possible that a single Identification will have multiple marks?  For example, would you have a single mark type, then multiple collar numbers?  Would you also potentially have different mark types in the same Identification?  Or are those possibilities so unlikely that we should not worry about them?

**Comment by mitch-fen** [comment]
@genkimaps That is definitely a possibility. An example would be some of the cathedral project images now, where we have a single identification with 14 mountain goats, 3 of which have collars with different discernible numbers. It's unlikely in my mind that we would have different mark types in one identification, but @wildcole might have more perspective on that possibility than I?
