### ISSUE TITLE
Field defaults in Ident window

### ISSUE THREAD

**Issue by mitch-fen** [genkimaps/wildcam#49]
The fields below should have the following default values:
Sex, age cat, behaviour, coat colour, snow: default null; 
count, group count: default 1

**Comment by genkimaps** [comment]
@mitch-fen 
Sex, age cat, behaviour, coat colour: these have "Select an Option" as the default, which is effectively the same as null.  If nothing is selected, the value will be null in the database.  Count, Group Count already have 1 as the default value.  Snow cover, I changed the default to blank [not yet deployed in production]. 

The only field that is carried over when the Identify window is opened again is "Identified By"
