### ISSUE TITLE
Add fields to camera checks

### ISSUE THREAD

**Issue by mitch-fen** [genkimaps/wildcam#54]
@genkimaps 

Add a new field Stopped Operating Date. 
We would like to also have "distance to trail" as a field within the camera settings section of the camera deployment page.

**Comment by genkimaps** [comment]
@mitch-fen 
Should this be a numeric field? (e.g. only measured in meters)  Or do you want to allow non-numeric descriptive text too?

**Comment by mitch-fen** [comment]
> @mitch-fen
> Should this be a numeric field? (e.g. only measured in meters) Or do you want to allow non-numeric descriptive text too?

@genkimaps numeric (in meters) should be all we need!
